export const countries = [
  {
    name: "Venezuela",
    code: "VE",
    phoneCode: "+58",
    flagEmoji: "🇻🇪",
  },
  {
    name: "Alemania",
    code: "DE",
    phoneCode: "+49",
    flagEmoji: "🇩🇪",
  },
 
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    flagEmoji: "🇦🇷",
  },

  {
    name: "Bélgica",
    code: "BE",
    phoneCode: "+32",
    flagEmoji: "🇧🇪",
  },

  {
    name: "Bolivia",
    code: "BO",
    phoneCode: "+591",
    flagEmoji: "🇧🇴",
  },
  {
    name: "Brasil",
    code: "BR",
    phoneCode: "+55",
    flagEmoji: "🇧🇷",
  },
  {
    name: "Canadá",
    code: "CA",
    phoneCode: " +1",
    flagEmoji: "🇨🇦",
  },
  {
    name: "Chile",
    code: "CL",
    phoneCode: "+56",
    flagEmoji: "🇨🇱",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneCode: "+57",
    flagEmoji: "🇨🇴",
  },

  {
    name: "Costa Rica",
    code: "CR",
    phoneCode: "+506",
    flagEmoji: "🇨🇷",
  },
  {
    name: "Croacia",
    code: "HR",
    phoneCode: "+385",
    flagEmoji: "🇭🇷",
  },
  {
    name: "Cuba",
    code: "CU",
    phoneCode: "+53",
    flagEmoji: "🇨🇺",
  },
  {
    name: "Dominica",
    code: "DM",
    phoneCode: "+1767",
    flagEmoji: "🇩🇲",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneCode: "+593",
    flagEmoji: "🇪🇨",
  },
  {
    name: "El Salvador",
    code: "SV",
    phoneCode: "+503",
    flagEmoji: "🇸🇻",
  },
  {
    name: "España",
    code: "ES",
    phoneCode: "+34",
    flagEmoji: "🇪🇸",
  },
  {
    name: "Estados Unidos de América",
    code: "US",
    phoneCode: "+1",
    flagEmoji: "🇺🇸",
  },
  {
    name: "Francia",
    code: "FR",
    phoneCode: "+33",
    flagEmoji: "🇫🇷",
  },
  {
    name: "Guatemala",
    code: "GT",
    phoneCode: "+502",
    flagEmoji: "🇬🇹",
  },
  {
    name: "Honduras",
    code: "HN",
    phoneCode: "+504",
    flagEmoji: "🇭🇳",
  },
  {
    name: "Italia",
    code: "IT",
    phoneCode: "+39",
    flagEmoji: "🇮🇹",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneCode: "+1876",
    flagEmoji: "🇯🇲",
  },
  {
    name: "México",
    code: "MX",
    phoneCode: "+52",
    flagEmoji: "🇲🇽",
  },
  {
    name: "Nicaragua",
    code: "NI",
    phoneCode: "+505",
    flagEmoji: "🇳🇮",
  },
  {
    name: "Panamá",
    code: "PA",
    phoneCode: "+507",
    flagEmoji: "🇵🇦",
  },
  {
    name: "Paraguay",
    code: "PY",
    phoneCode: "+595",
    flagEmoji: "🇵🇾",
  },
  {
    name: "Perú",
    code: "PE",
    phoneCode: "+51",
    flagEmoji: "🇵🇪",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    flagEmoji: "🇵🇹",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    phoneCode: "+1939",
    flagEmoji: "🇵🇷",
  },
  {
    name: "Reino Unido",
    code: "GB",
    phoneCode: "+44",
    flagEmoji: "🇬🇧",
  },

  {
    name: "República Dominicana",
    code: "DO",
    phoneCode: "+1849",
    flagEmoji: "🇩🇴",
  },
  {
    name: "Rusia",
    code: "RU",
    phoneCode: "+7",
    flagEmoji: "🇷🇺",
  },
  {
    name: "Uruguay",
    code: "UY",
    phoneCode: "+598",
    flagEmoji: "🇺🇾",
  },
];
